import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Karnataka Auto Union</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Karnataka Auto Union.
        </h1>

        <p className={styles.description}>
          Let's get started.
        </p>

        <div className={styles.grid}>
          <a href="/admin/register" className={styles.card}>
            <h2>Registration &rarr;</h2>
            <p>Complete payment for membership.</p>
          </a>

          <a href="" className={styles.card}>
            <h2>Renewal &rarr;</h2>
            <p>Renew your expiring membership.</p>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <h2>FAQs &rarr;</h2>
            <p>Discover how to use this webapp.</p>
          </a>

          <a
            href=""
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Feedback &rarr;</h2>
            <p>
              We would love to hear from you.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
